name              "rosetta"
maintainer        "Yifeng Jiang"
maintainer_email  "uprushworld at gmail.com"
license           "Apache 2.0"
description       "Sets up Rosetta components"
version           "1.0.0"
supports          "ubuntu"
recipe            "agent", "Sets up rosetta agent"
